### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ArdiaD** [ArdiaD/DEoptim#29]
Please @k-m-m make sure citation files, documentation, etc, I made in April 2020 will not be overwritten in your changes for 2.2-7. Thx

**Comment by k-m-m** [comment]
I am working from the latest version of the files -- I see your changes and they will not be overwritten.

**Comment by joshuaulrich** [comment]
@k-m-m, the latest version was cd9818822050cb2e0b8ea97a8452daf1f347947e when you started working on this. I'm re-opening this because there are several documentation (and citation, bibliograpy, etc.) changes David made in April 2020 may have been reverted in part or total in commit 53341917773a40f617694aba6ec74ec28bed6cf1.

My hypothesis is that David thought that commit (which appears to be the state of things in the DEoptim_2.2-5 tarball) contained the changes he had made in April 2020 because he asked for a release at that time in #9. I don't know which of those changes made it into 2.2-5 a year later on 2021-05-05.

David, can you confirm that the various documentation files should be as-of fae02a7e1ae7a63d09a88240ada6d9ff1cce91a2?

**Comment by k-m-m** [comment]
Josh is right that is was not so easy as I thought at first.  As I add back the parallel option, etc., that were offered via changes in DEoptim.R, and presumably also reflected in the doc., I'll reconcile with fae02a7.

**Comment by joshuaulrich** [comment]
To clarify, I'm using "documentation" in a broad sense. David might have changed the citation file, a bibliography file, etc... not just .Rd files.

**Comment by k-m-m** [comment]
I understand.  I'll try to look at all files.

**Comment by ArdiaD** [comment]
Yes, @joshuaulrich is right; thx for pointing this.

**Comment by k-m-m** [comment]
Things should be reconciled now, I hope.  A few notes - 
+ we use DOIs not URLs in the Rd files
+ I changed Description in DESCRIPTION to be better formatted
+ I'm attaching the pdf manual 
[DEoptim-master.pdf](https://github.com/ArdiaD/DEoptim/files/9916707/DEoptim-master.pdf) -pls let me know or make changes if you spot issues

**Comment by ArdiaD** [comment]
good for me @k-m-m thx
